package com.gateway.service;

import com.gateway.api.dto.GeminiRequest;
import com.gateway.api.dto.GeminiResponse;
import java.util.List;

/**
 * Emulator client for Gemini API - returns mock responses for testing and
 * development.
 * Useful when you don't have a valid API key or want to test without making
 * real API calls.
 */
public class EmulatorGeminiClient implements GeminiClient {

    @Override
    public GeminiResponse sendRequest(GeminiRequest request) {
        // Generate a mock response based on the system instruction and document
        final var mockResponseText = generateMockResponse(request.systemInstruction(), request.document());

        // Build GeminiResponse structure using nested records
        final var part = new GeminiResponse.Part(mockResponseText);
        final var content = new GeminiResponse.Content(
                List.of(part),
                "assistant");
        final var candidate = new GeminiResponse.Candidate(
                content,
                "STOP");

        return new GeminiResponse(List.of(candidate));
    }

    /**
     * Generates a mock response based on system instruction using pattern matching.
     * Uses switch expression for cleaner, more maintainable pattern matching.
     */
    private String generateMockResponse(String systemInstruction, String document) {
        return switch (detectPattern(systemInstruction.toLowerCase())) {
            case SUMMARIZE -> "This is a mock summary of the provided document. In production, this would be " +
                    "generated by the Gemini API. The document appears to contain important information " +
                    "that would be useful for analysis and understanding key concepts.";

            case EXTRACT -> "Mock extracted information:\n" +
                    "- Key Point 1: Details about the main topic\n" +
                    "- Key Point 2: Important supporting information\n" +
                    "- Key Point 3: Additional relevant details\n" +
                    "This is emulated data for testing purposes.";

            case ANALYZE -> "Analysis Results (Emulated):\n" +
                    "The provided document has been analyzed. Key findings include structured " +
                    "content with clear sections. The document appears well-organized and contains " +
                    "relevant information for processing. This is a mock response suitable for testing.";

            case TRANSLATE -> "Mock translation of the document content. In a production environment, " +
                    "this would contain the actual translated text from the Gemini API. " +
                    "For testing purposes, this serves as a placeholder response.";

            case UNKNOWN -> "Mock response from Gemini emulator. This is a simulated response for development and " +
                    "testing purposes. In production, this would be replaced with an actual response from the " +
                    "Gemini API. The emulator mode is useful when you don't have a valid API key or want to " +
                    "test the application without making real API calls.";
        };
    }

    /**
     * Detects the pattern from system instruction to determine response type
     */
    private ResponsePattern detectPattern(String instruction) {
        if (instruction.contains("summarize") || instruction.contains("summary")) {
            return ResponsePattern.SUMMARIZE;
        } else if (instruction.contains("extract") || instruction.contains("extraction")) {
            return ResponsePattern.EXTRACT;
        } else if (instruction.contains("analyze") || instruction.contains("analysis")) {
            return ResponsePattern.ANALYZE;
        } else if (instruction.contains("translate") || instruction.contains("translation")) {
            return ResponsePattern.TRANSLATE;
        }
        return ResponsePattern.UNKNOWN;
    }

    /**
     * Pattern enum for switch expression matching
     */
    private enum ResponsePattern {
        SUMMARIZE, EXTRACT, ANALYZE, TRANSLATE, UNKNOWN
    }
}
