package com.gateway.service;

import com.gateway.api.dto.GeminiResponse;
import com.gateway.api.dto.GeminiResponse.Candidate;
import com.gateway.api.dto.GeminiResponse.Content;
import com.gateway.api.dto.GeminiResponse.Part;
import com.gateway.exception.GatewayException;
import java.util.List;

/**
 * Emulator client for Gemini API - returns mock responses for testing and development.
 * Useful when you don't have a valid API key or want to test without making real API calls.
 */
public class EmulatorGeminiClient implements GeminiClient {
    
    @Override
    public GeminiResponse sendRequest(String prompt, String modelName) throws GatewayException {
        // Generate a mock response based on the prompt content
        final var mockResponseText = generateMockResponse(prompt);
        
        // Build GeminiResponse structure
        final var part = new Part(mockResponseText);
        final var content = new Content(
            List.of(part),
            "assistant"
        );
        final var candidate = new Candidate(
            content,
            "STOP"
        );
        
        return new GeminiResponse(List.of(candidate));
    }

    /**
     * Generates a mock response based on the input prompt.
     * This is a simple emulator - in a real scenario you might want more sophisticated logic.
     */
    private String generateMockResponse(String prompt) {
        // Basic pattern matching to provide contextual responses
        final var lowerPrompt = prompt.toLowerCase();
        
        if (lowerPrompt.contains("summarize") || lowerPrompt.contains("summary")) {
            return "This is a mock summary of the provided document. In production, this would be " +
                   "generated by the Gemini API. The document appears to contain important information " +
                   "that would be useful for analysis and understanding key concepts.";
        }
        
        if (lowerPrompt.contains("extract") || lowerPrompt.contains("extract information")) {
            return "Mock extracted information:\n" +
                   "- Key Point 1: Details about the main topic\n" +
                   "- Key Point 2: Important supporting information\n" +
                   "- Key Point 3: Additional relevant details\n" +
                   "This is emulated data for testing purposes.";
        }
        
        if (lowerPrompt.contains("analyze") || lowerPrompt.contains("analysis")) {
            return "Analysis Results (Emulated):\n" +
                   "The provided document has been analyzed. Key findings include structured " +
                   "content with clear sections. The document appears well-organized and contains " +
                   "relevant information for processing. This is a mock response suitable for testing.";
        }
        
        if (lowerPrompt.contains("translate") || lowerPrompt.contains("translation")) {
            return "Mock translation of the document content. In a production environment, " +
                   "this would contain the actual translated text from the Gemini API. " +
                   "For testing purposes, this serves as a placeholder response.";
        }
        
        // Default response for any other prompt
        return "Mock response from Gemini emulator. This is a simulated response for development and " +
               "testing purposes. In production, this would be replaced with an actual response from the " +
               "Gemini API. The emulator mode is useful when you don't have a valid API key or want to " +
               "test the application without making real API calls.";
    }
}
